#!python3

import json, sys, os
from urllib import request
from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('-c', '--cookie', help='use cookies', type=str, default='', metavar='COOKIES', dest='cookies')
parser.add_argument('-o', '--output', help='output name', type=str, default='', metavar='NAME', dest='output')
parser.add_argument('-r', '--referer', help='referer', default='', type=str, metavar='URL', dest='referer')
parser.add_argument('-R', '--rpc', help='aria2 rpc', type=str, default='http://127.0.0.1:6800/jsonrpc', metavar='URL', dest='rpc')
parser.add_argument('URIs', nargs='+', help='URIs', type=str, default='', metavar='URI')
opts = parser.parse_args()
jsondict = {'jsonrpc':'2.0', 'id':'aria2rpc', 'method':'aria2.addUri', 'params':[opts.URIs]}

aria2opts = {'continue':'true', 'max-connection-per-server':16, 'split':16, 'min-split-size':'1M'}
if opts.output:
	aria2opts['out'] = opts.output
if opts.referer:
	aria2opts['referer'] = opts.referer
if opts.cookies:
	aria2opts['header'] = ['Cookie: %s' % opts.cookies]
if '.baidu' in opts.URIs[0]:
	aria2opts['user-agent'] = 'netdisk;5.5.2.0;PC;PC-Windows;10.0.14393;WindowsBaiduNetdisk'
	aria2opts['referer'] = 'http://pan.baidu.com/disk/home'

jsondict['params'].append(aria2opts)
jsonreq = json.dumps(jsondict).encode('utf-8')
request.urlopen(opts.rpc, jsonreq)
